### PR TITLE
Change namespace to "Amazon.IonObjectMapper"

### PR DESCRIPTION
**Pull request by byronlin13**
*Issue #, if available:*

*Description of changes:*
The current Ion .NET libraries have the name spaces:
* `Amazon.IonDotnet`
* `Amazon.IonHashDotnet`

To be consistent with this namespace pattern, we are updating the object mapper namespace from `Amazon.Ion.ObjectMapper` to `Amazon.IonObjectMapper`

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by HomayounA — COMMENTED** [review]
lgtm

**Comment by byronlin13** [comment]
I think we should hold off this change until most PRs have been merged because this changes every file and will rebasing will be tricky

**Comment by kylepbit** [comment]
@byronlin13 - can we close this PR for now until we intend to move forward with it?

**Comment by byronlin13** [comment]
Closing PR for now.

**Pull request closed without merging**
